# config.yaml
rag_doomstead:
  embedding_model: "sentence-transformers/all-mpnet-base-v2"
  chunk_size: 800
  chunk_overlap: 150
  code_dirs:
    py:
      - "/var/www/html/doomsteadRAG/assets/py"
    php:
      - "/var/www/html/homedog/doomstead"
      - "/var/www/html/homedog/doomstead/Themes"
      - "/var/www/html/homedog/doomstead/Themes/doomstead"
      - "/var/www/html/homedog/doomstead/Sources"
      - "/var/www/html/homedog"
      - "/var/www/html/homedog/assets/php"
      - "/var/www/html/doomsteadRAG/assets/php"
    js:
      - "/var/www/html/homedog/doomstead/Themes/doomstead/scripts"
      - "/var/www/html/homedog/assets/js"
      - "/var/www/html/doomsteadRAG/assets/js"
    css:
      - "/var/www/html/homedog/doomstead/Themes/doomstead/css"
      - "/var/www/html/homedog/assets/css"
      - "/var/www/html/doomsteadRAG/assets/css"

  vector_db_path: "/var/www/html/doomsteadRAG/assets/data"

